version: '3.8'

services:
  vector-db:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    volumes:
      - vector-db-data:/var/lib/qdrant
  
  healthcheck:
    image: curlimages/curl:latest
    entrypoint: ["/bin/sh", "-c", "--", "sleep 40;"]
    depends_on:
      - vector-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://vector-db:6333/readyz"]
      interval: 10s
      timeout: 2s
      retries: 3
  
  index-builder:
    build: 
      context: ./index-builder
    volumes:
      - ./index-builder:/usr/src/app
    env_file: ./.env
    depends_on:
      healthcheck:
        condition: service_healthy

volumes:
  vector-db-data:
