services:
  nuxt-app:
    container_name: ${COMPOSE_PROJECT_NAME}-nuxt-app
    build:
      context: .
      dockerfile: nuxter-config/Dockerfile.nuxt-app
      args:
        APP_ENV: ${APP_ENV}
    env_file: nuxter-config/nuxt-app.${APP_ENV}.env
    restart: always
    volumes:
      - .output.${APP_ENV}/server/db:/opt/nuxter/.output/server/db
    networks:
      - caddy_nuxt_app
      - vector_db

  vector-db:
    container_name: ${COMPOSE_PROJECT_NAME}-vector-db
    image: qdrant/qdrant
    restart: always
    volumes:
      - vector-db-data:/var/lib/qdrant
    networks:
      - vector_db

volumes:
  vector-db-data:

networks:
  caddy_nuxt_app:
    name: ${COMPOSE_PROJECT_NAME}_caddy_nuxt_app
    external: true
  vector_db:
    name: ${COMPOSE_PROJECT_NAME}_vector_db
    external: true
