version: '3.8'

services:
  nuxt-app:
    container_name: ${COMPOSE_PROJECT_NAME}-nuxt-app
    build:
      context: .
      dockerfile: nuxter-config/Dockerfile.nuxt-app
      args:
        APP_ENV: ${APP_ENV}
    env_file: nuxter-config/nuxt-app.${APP_ENV}.env
    restart: unless-stopped
    volumes:
      - .output.${APP_ENV}/server/db:/opt/nuxter/.output/server/db
    networks:
      - caddy_nuxt_app

networks:
  caddy_nuxt_app:
    name: ${COMPOSE_PROJECT_NAME}_caddy_nuxt_app
    external: true
