on:
  push:
    branches:
      - stage
jobs:
  build-nuxt:
    uses: ./.github/workflows/deploy-nuxt-app.yml
    with:
      app_name: vue-ai-tools
      app_env: staging
    secrets:
      DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
      DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
      DROPLET_KEY: ${{ secrets.DROPLET_KEY }}
