on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage
jobs:
  build-nuxt:
    uses: chris-paganon/nuxter/.github/workflows/deploy-nuxt-app.yml
    with:
      app_name: vue-ai-tools
    secrets:
      DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
      DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
      DROPLET_KEY: ${{ secrets.DROPLET_KEY }}
