on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage
jobs:
  build-nuxt:
    name: Build nuxt on node and send files to Droplet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Use Node
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '16.18.0'
    - name: npm install & build
      run: |
        npm ci
        npm run build
    - name: rsync to Droplet
      uses: contention/rsync-deployments@v2.0.0
      with:
        USER: ${{ secrets.DROPLET_USERNAME }}
        HOST: ${{ secrets.DROPLET_HOST }}
        DEPLOY_KEY: ${{ secrets.DROPLET_KEY }}
        LOCALPATH: .output/
        REMOTEPATH: /opt/nuxter/vue-ai-tools/.output.staging
        FLAGS: --delete -d
    - name: restart docker on Droplet
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
        ssh-add - <<< "${{ secrets.DROPLET_KEY }}"
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} "cd /opt/nuxter/vue-ai-tools/nuxter-config && docker compose -f vue-ai-tools-staging-compose.yml up --build nuxt-app && exit"
